name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"   # jalan tiap hari jam 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # ⬅️ penting biar bisa push

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update log file
        run: |
          echo "Daily commit at $(date)" >> log.txt
          git config user.name "lindena21"
          git config user.email "lindenaanwar@gmail.com"
          git add log.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"
          git push
